export const categories = [
  "eletrônicos",
  "informática",
  "celulares",
  "eletrodomésticos",
  "móveis",
  "decoração",
  "roupas",
  "calçados",
  "acessórios",
  "beleza",
  "saúde",
  "brinquedos",
  "esportes",
  "fitness",
  "alimentos",
  "bebidas",
  "pet shop",
  "livros",
  "instrumentos musicais",
  "ferramentas",
  "autopeças",
  "jardinagem",
  "papelaria",
  "artigos de festa",
  "games",
  "acessórios de informática",
  "câmeras e fotografia",
  "eletrônicos portáteis",
  "relógios",
  "joias",
  "bolsas e mochilas",
  "produtos naturais",
  "higiene pessoal",
  "perfumes",
  "moda praia",
  "moda infantil",
  "moda masculina",
  "moda feminina",
  "tênis e sneakers",
  "roupa de cama",
  "mesa e banho",
  "utensílios de cozinha",
  "smart home",
  "brinquedos educativos",
  "decoração infantil",
  "camping e aventura",
  "artigos de viagem",
  "veículos",
  "materiais de construção",
  "iluminação",
  "segurança e câmeras",
];
