import {
  Zap,
  Monitor,
  Smartphone,
  Home,
  Sofa,
  Palette,
  Shirt,
  Footprints,
  Watch,
  Sparkles,
  Heart,
  Baby,
  Dumbbell,
  Activity,
  Apple,
  Coffee,
  Dog,
  Book,
  Music,
  Wrench,
  Car,
  Flower,
  PenTool,
  PartyPopper,
  Gamepad2,
  Mouse,
  Camera,
  Radio,
  Clock,
  Diamond,
  ShoppingBag,
  Leaf,
  Droplets,
  SprayCan,
  Waves,
  User,
  Users,
  Footprints as Sneakers,
  Bed,
  UtensilsCrossed,
  ChefHat,
  Lightbulb,
  GraduationCap,
  HomeIcon,
  Tent,
  BriefcaseBusiness,
  Truck,
  Hammer,
  Lightbulb as Light,
  Shield,
} from "lucide-react";

export const categories = [
  { name: "eletrônicos", icon: Zap },
  { name: "informática", icon: Monitor },
  { name: "celulares", icon: Smartphone },
  { name: "eletrodomésticos", icon: Home },
  { name: "móveis", icon: Sofa },
  { name: "decoração", icon: Palette },
  { name: "roupas", icon: Shirt },
  { name: "calçados", icon: Footprints },
  { name: "acessórios", icon: Watch },
  { name: "beleza", icon: Sparkles },
  { name: "saúde", icon: Heart },
  { name: "brinquedos", icon: Baby },
  { name: "esportes", icon: Dumbbell },
  { name: "fitness", icon: Activity },
  { name: "alimentos", icon: Apple },
  { name: "bebidas", icon: Coffee },
  { name: "pet shop", icon: Dog },
  { name: "livros", icon: Book },
  { name: "instrumentos musicais", icon: Music },
  { name: "ferramentas", icon: Wrench },
  { name: "autopeças", icon: Car },
  { name: "jardinagem", icon: Flower },
  { name: "papelaria", icon: PenTool },
  { name: "artigos de festa", icon: PartyPopper },
  { name: "games", icon: Gamepad2 },
  { name: "acessórios de informática", icon: Mouse },
  { name: "câmeras e fotografia", icon: Camera },
  { name: "eletrônicos portáteis", icon: Radio },
  { name: "relógios", icon: Clock },
  { name: "joias", icon: Diamond },
  { name: "bolsas e mochilas", icon: ShoppingBag },
  { name: "produtos naturais", icon: Leaf },
  { name: "higiene pessoal", icon: Droplets },
  { name: "perfumes", icon: SprayCan },
  { name: "moda praia", icon: Waves },
  { name: "moda infantil", icon: Baby },
  { name: "moda masculina", icon: User },
  { name: "moda feminina", icon: Users },
  { name: "tênis e sneakers", icon: Sneakers },
  { name: "roupa de cama", icon: Bed },
  { name: "mesa e banho", icon: UtensilsCrossed },
  { name: "utensílios de cozinha", icon: ChefHat },
  { name: "smart home", icon: Lightbulb },
  { name: "brinquedos educativos", icon: GraduationCap },
  { name: "decoração infantil", icon: HomeIcon },
  { name: "camping e aventura", icon: Tent },
  { name: "artigos de viagem", icon: BriefcaseBusiness },
  { name: "veículos", icon: Truck },
  { name: "materiais de construção", icon: Hammer },
  { name: "iluminação", icon: Light },
  { name: "segurança e câmeras", icon: Shield },
];
